name: Release
description: Perform a Quarkus release
labels: kind/release
body:
  - type: markdown
    attributes:
      value: |
        This form will perform a Quarkus release. Use with care and only if you know what you are doing.

        **IMPORTANT** Only Quarkus releasers can actually start a release.
  - type: input
    id: branch
    validations:
      required: true
    attributes:
      label: Branch
      description: >-
        The name of the branch to release (e.g. `3.5`). Do **NOT** release from `main`.
  - type: input
    id: qualifier
    attributes:
      label: Qualifier
      description: >-
        The optional **preview** qualifier for the release (for instance `CR1`). The `Final` qualifier is added automatically for branches that require it.
  - type: checkboxes
    id: major
    attributes:
      label: Major version
      description: >-
        Whether the release is a major new version (e.g. `4.0.0`). Use with care.
      options:
        - label: This release is a major version.
          required: false
