name: Continue release

on:
  issue_comment:
    types: [created]

permissions:
  actions: write
  issues: write

defaults:
  run:
    shell: bash

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Install lz4
        run: sudo apt-get -y install lz4
      - name: Check out quarkusio/quarkus-release
        uses: actions/checkout@v4
        with:
          repository: quarkusio/quarkus-release
      - name: Check out quarkus-release/release to release
        uses: actions/checkout@v4
        with:
          repository: quarkus-release/release
          path: release
      - name: Set up Java environment
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          # we do not define the server credentials here as we need to keep the github repository credentials around for executing the GitHub Action
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
      - name: Get previous workflow run id
        id: get-workflow-run-id
        uses: quarkusio/conversational-release-action@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          action: get-workflow-run-id
      - name: Download work artifact
        run: |
          gh run download ${{ steps.get-workflow-run-id.outputs.workflow-run-id }} -n work
          tar -I lz4 -xf work.tar.lz4 --directory ../
        working-directory: release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Push Maven server settings
        run: |
          sed -i "s@</servers>@<server><id>sonatype-nexus-release</id><username>${{ secrets.MAVEN_SERVER_USERNAME }}</username><password>${{ secrets.MAVEN_SERVER_PASSWORD }}</password></server></servers>@" ~/.m2/settings.xml
      - name: Set up JBang
        uses: jbangdev/setup-jbang@main
      - name: Continue release
        id: release
        uses: quarkusio/conversational-release-action@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PRIVATE_PASSPHRASE }}
          RELEASE_GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}
          JRELEASER_GITHUB_TOKEN: ${{ secrets.JRELEASER_GITHUB_TOKEN }}
          JRELEASER_CHOCOLATEY_GITHUB_TOKEN: ${{ secrets.JRELEASER_CHOCOLATEY_GITHUB_TOKEN }}
          JRELEASER_CHOCOLATEY_GITHUB_USERNAME: ${{ secrets.JRELEASER_CHOCOLATEY_GITHUB_USERNAME }}
          JRELEASER_HOMEBREW_GITHUB_TOKEN: ${{ secrets.JRELEASER_HOMEBREW_GITHUB_TOKEN }}
          JRELEASER_HOMEBREW_GITHUB_USERNAME: ${{ secrets.JRELEASER_HOMEBREW_GITHUB_USERNAME }}
          JRELEASER_SDKMAN_CONSUMER_KEY: ${{ secrets.JRELEASER_SDKMAN_CONSUMER_KEY }}
          JRELEASER_SDKMAN_CONSUMER_TOKEN: ${{ secrets.JRELEASER_SDKMAN_CONSUMER_TOKEN }}
      - name: Create archive for work directory
        if: always()
        run: tar -I lz4 -cf work.tar.lz4 work
      - name: Upload work directory archive as artifact
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: work
          path: work.tar.lz4
      - name: Post interaction comment
        uses: quarkusio/conversational-release-action@main
        if: always()
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          action: post-interaction-comment
          interaction-comment: ${{ steps.release.outputs.interaction-comment }}
