name: Release

on:
  issues:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
          server-id: 'sonatype-nexus-release'
          server-username: ${{ secrets.MAVEN_SERVER_USERNAME }}
          server-password: ${{ secrets.MAVEN_SERVER_PASSWORD }}
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
      - name: Set up JBang
        uses: jbangdev/setup-jbang@main
      - uses: quarkusio/conversational-release-action@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PRIVATE_PASSPHRASE }}
